services:
  - type: web
    name: login-backend-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_DETAILS
        value: mongodb+srv://areebailyas4321_db_user:KtzA8iTX94fEXDUN@cluster0.xyz.mongodb.net/?retryWrites=true&w=majority
      - key: SECRET_KEY
        value: KUZTfth6hZ7lol5MQ5fGZ4TRTiCLfxhCR0c5vE35o4M
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
